# Generated by Django 4.2.3 on 2023-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_booking_bookingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
    ]
